spring:
  application:
    name: myspringboot
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false

server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 9090



mybatis:
  type-aliases-package: com.kk.entity
  mapper-locations: classpath:mapper/*.xml


---
#开发配置
#autoReconnect        mysql超过8小时没有操作,会自动断开连接,该属性可配置是否重新连接？
#failOverReadOnly     自动重连成功后，连接是否设置为只读？
#useSSL=false         MySQL在高版本需要指明是否进行SSL连接？
#配置thymeleaf关闭缓存

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    #最大连接个数
    maxActive: 20
    #初始化连接个数
    initialSize: 1
    #获取连接时最大等待时间，单位毫秒。
    maxWait: 60000
    #最小空闲连接个数
    minIdle: 1
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。
    validationQuery: select 'x'
    #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    #最大缓存数
    maxOpenPreparedStatements: 20